replicaCount: 1

image:
  repository: ghcr.io/armanfeyzi/helm-watch
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  logLevel: info
  reconcileEvery: 30s
  repoCacheTTL: 5m
